services:
  # The Fastify Backend API
  - type: web
    name: amar-space-api
    env: docker
    dockerfilePath: ./docker/api.Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: AUTH_BASE_URL
        sync: false

  # The Next.js Frontend Web
  - type: web
    name: amar-space-web
    env: docker
    dockerfilePath: ./docker/web.Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      # You need to fill this in manually via the Render dashboard once the amar-space-api URL is known
      - key: NEXT_PUBLIC_API_URL
        sync: false
