services:
  # The Fastify Backend API
  - type: web
    name: amar-space-api
    env: docker
    plan: free
    dockerfilePath: ./docker/api.Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: AUTH_BASE_URL
        sync: false
